name: flutter_github_scripts
description: Scripts to provide reports on Flutter's code health.
publish_to: none
version: 0.0.2

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  args: ^2.2.0
  csv:  ^5.0.0
  glob: ^2.0.1
  graphql: ^5.1.3
  http: ^0.13.5
  intl: ^0.18.0
  path: ^1.8.0
  quiver: ^3.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.17.12
